### ISSUE TITLE
Issue on main.py about kafka topic

### ISSUE THREAD

**Issue by sbendhiba** [emumba-com/live_twitter_sentiment_analysis#2]
In **Thread 3**: looks for rolling mean from spark streaming.
**KAFKA_TOPIC_FOR_SENTIMENT** is used instead of **KAFKA_TOPIC_FOR_AVERAGE**, so the final plot is using real time sentiments and not the rolling average from kafka.

**Comment by harishasan** [comment]
Fixed: https://github.com/emumba-com/live_twitter_sentiment_analysis/commit/e6b681099f0c533397d6e7385a28a55e6f4d7392
